pipeline {
  agent{
      kubernetes {
        yamlFile 'cicd/pods.yml'
      }
  }
  stages {
    stage("Test 1") {
      steps {
          container('node-runner') {
            sh "npm install"
            sh "npm test"
          }
      }
    }
    stage("Test 2") {
      steps {
          container('node-runner') {
            input 'Do you approve Second Testing?'
            sh "npm test"
          }
      }
    }
  }
  
}
