apiVersion: v1
kind: Pod
metadata:
  name: data-collab-ci
spec:
  containers:
  - name: node-runner
    image: node:lts
    resources:
      limits:
        memory: "1024Mi"
        cpu: "500m"
    command:
      - sleep
    args:
      - infinity
